version: "3"
services:
  publisher:
    build:
      dockerfile: "publisher.Dockerfile"
      context: "."
    container_name: "publisher"
    depends_on:
      - "kafka"
    environment:
      KAFKA_HOST_PORT: "kafka:9092"
      KAFKA_TOPIC: "celcius-readings"
  subscriber:
    build:
      dockerfile: "subscriber.Dockerfile"
      context: "."
    container_name: "subscriber"
    depends_on:
      - "kafka"
    environment:
      KAFKA_HOST_PORT: "kafka:9092"
      KAFKA_TOPIC: "celcius-readings"
  kafka:
    depends_on:
      - "zookeeper"
    container_name: "kafka"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: "kafka"
      KAFKA_ADVERTISED_PORT: "9092"
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
    image: "wurstmeister/kafka"
    ports:
      - "9092:9092"
  zookeeper:
    container_name: "zookeeper"
    image: "wurstmeister/zookeeper"
    ports:
      - "2181:2181"
